{
    ":root": {
        "backgroundImage": "url('https://imageio.forbes.com/specials-images/imageserve/1165871313/2019-Lollapalooza---Day-2/960x0.jpg')",
        "backgroundImageBlur": "3px",
        "backgroundImageSize": "cover",
        "backgroundImagePosition": "center",
        "popoutImage": "var(--background-image)",
        "popoutImageBlur": "1px",
        "popoutImageSize": "cover",
        "popoutImagePosition": "center",
        "overlayImage": "var(--background-image)",
        "overlayImageBlur": "5px",
        "overlayImageSize": "cover",
        "overlayImagePosition": "center",
        "homeButtonImage": "url('https://imageio.forbes.com/specials-images/imageserve/1165871313/2019-Lollapalooza---Day-2/960x0.jpg')",
        "homeButtonSize": "cover",
        "homeButtonPosition": "center",
        "serverlistBrightness": 0.56,
        "leftBrightness": 0.52,
        "middleBrightness": 0.64,
        "rightBrightness": 0,
        "overlayBrightness": 0.54,
        "gradientPrimary": [240, 17, 183],
        "gradientSecondary": [0, 0, 0],
        "linkColour": "#EC00E2",
        "scrollbarColour": ["rgb(7,7,7,0)"],
        "gradientDirection": '192deg',
        'tintColour': [255, 51, 159],
		'tintBrightness': 0,
		'font': 0,
		'windowPadding': '10px',
		'windowRoundness': '21px',
		'updateNotice1': 'none',
		'columns': 2,
		'guildgap': '3',
		'aligndms': '1'
    }
}